name: NotWordleWorkflow

on:
  push

jobs:
  build:
    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: |
        mkdir ${{github.workspace}}/build && cd ${{github.workspace}}/build
        cmake ..

    - name: Build
      run: |
        cd  ${{github.workspace}}/build
        make -j 5
  test:
    needs: build
    steps:
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest
      
    - name : Generate Code Coverage
      working-directory: ${{github.workspace}}/build
      run: make coverage_NotWordleUT
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ${{github.workspace}}/build
        files: ./build/coverage_NotWordleUT_dir.xml
        name: codecov-umbrella
        fail_ci_if_error: false
        verbose: true
